### ISSUE TITLE
插件冲突修复方法 ，当ComfyUI_Fooocus和ComfyUI_UltimateSDUpscale插件冲突时

### ISSUE THREAD

**Issue by klossm** [17Retoucher/ComfyUI_Fooocus#10]
找到下面这个路径的这个文件 __init__.py    删了，init名称左右2边是有下划线的，这里显示不了，路径如下，不保证不会引起其它问题，希望有大佬补充
ComfyUI\custom_nodes\ComfyUI_Fooocus\py\modules

**Comment by 17Retoucher** [comment]
已经修复
